### ISSUE TITLE
QR Result On Same Scanning Screen

### ISSUE THREAD

**Issue by praveenshharma** [GuoJinyu/SimpleZXing#1]
@GuoJinyu what to do if we have to get our qr result on same scanning screen ?

**Comment by GuoJinyu** [comment]
@praveenshharma you just need customize your requirement，you should do these steps:
1. in [capture.xml](https://github.com/GuoJinyu/SimpleZXing/blob/master/simplezxing/src/main/res/layout/capture.xml), add your display view.
2. in [CaptureActivity.java](https://github.com/GuoJinyu/SimpleZXing/blob/master/simplezxing/src/main/java/com/acker/simplezxing/activity/CaptureActivity.java) handleDecode() method, get the qr result and display it on step1, and remember do not finish the activity.

**Comment by praveenshharma** [comment]
Hi GuoJinyu, thanx for your replying
Can you give me a solution on your answer on Zxing Portrait mode ?

**Comment by praveenshharma** [comment]
Thankyou @GuoJinyu 
Now to I want to animate laser in OnDraw() so I did this..

        private void drawMovingLaser(Canvas canvas, Rect framingRect, int middle, Paint mLaserPaint){

        boolean isAnimatedTop = false;
        int speed = 10;
        int acc = 10;
        int lineHeight = 8;
        int change; // or difference

        if (linePosition == 0) {
            linePosition = framingRect.top;
        }
        if (isAnimatedTop) {
            // is animating in first block
            if (linePosition > framingRect.top && linePosition <= middle) {
                change = speed - (speed * acc) / 100;
                linePosition -= change;
            }

            // is animating in second block
            if (linePosition > middle) {// && scannerLineHeight >= (framingRect.bottom)) {
                change = speed + (speed * acc) / 100;
                linePosition -= change;
            }
            if (linePosition <= framingRect.top) {
                isAnimatedTop = false;
            }
        } else {
            // animating to down side
            // is animating in first block from down
            if (linePosition < framingRect.bottom && linePosition > middle) {
                change = speed - (speed * acc) / 100;
                linePosition += change;
            }

            // is animating in second block from down
            if (linePosition <= middle) {// && scannerLineHeight >= (framingRect.top)) {
                change = speed + (speed * acc) / 100;
                linePosition += change;
            }
            if ((linePosition + lineHeight) >= framingRect.bottom) {
                isAnimatedTop = true;
            }
        }
        canvas.drawRect(framingRect.left + 2, linePosition, framingRect.right - 1, linePosition + lineHeight, mLaserPaint);
    }


Line is animating but somehow it is flickering, I tried a lot but it is not animating smoothly. Can you help me out ?

**Comment by GuoJinyu** [comment]
@praveenshharma The "flickering" is caused by the interval of onDraw() is too long for your desired 
 laser animation. 
then at the end of onDraw() you should see this code to REDRAW the PARTIAL view, so adjust the parameter to which you want.
```java
            // Request another update at the animation interval, but only repaint the laser line,
            // not the entire viewfinder mask.
            postInvalidateDelayed(ANIMATION_DELAY,
                    frame.left - POINT_SIZE,
                    frame.top - POINT_SIZE,
                    frame.right + POINT_SIZE,
                    frame.bottom + POINT_SIZE);
```

**Comment by praveenshharma** [comment]
@GuoJinyu Thanks a lot, it was really helpful.
