### ISSUE TITLE
调用的时候就失败

### ISSUE THREAD

**Issue by xinshengBoy** [GuoJinyu/SimpleZXing#2]
点击按钮调用就会报错
java.lang.RuntimeException: Unable to resume activity {com.example.zhongzhihua/com.acker.simplezxing.activity.CaptureActivity}: java.lang.ClassCastException: com.example.zhongzhihua.scan.view.ViewfinderView cannot be cast to com.acker.simplezxing.view.ViewfinderView

Caused by: java.lang.ClassCastException: com.example.zhongzhihua.scan.view.ViewfinderView cannot be cast to com.acker.simplezxing.view.ViewfinderView

楼主瞅瞅这是什么原因

**Comment by GuoJinyu** [comment]
@zhongzhihuashanghai 错误信息已经写的非常明白了，你改了包名，但是代码里某个地方没有改，比如layout的xml
