### ISSUE TITLE
Need Barcode Format type in the result

### ISSUE THREAD

**Issue by amahouachi** [GuoJinyu/SimpleZXing#3]
Hello
I am trying to use your library but I need in addition to barcode the barcode format.
I saw in CaptureActivity you are just returning the barcode.
I tried to extend your activity but it is "final".
Then tried to duplicate the activity code but cannot since CaptureActivityHandler is not public.
I think there are few others which are not public neither.

Is there a specific reason why it is like that? Could it be changed to be more extension-friendly? If not can you tell me a simple way to achieve my goal?

Thanks

**Comment by GuoJinyu** [comment]
I do not understand what does "barcode the barcode format" mean？
But I think if you want custom your scan demand，you'd better clone this project and copy the simplezxing module to your own project and code it.

**Comment by amahouachi** [comment]
I mean you are returning the value of barcode. I need also the barcode format.
